### ISSUE TITLE
Order history & cache for updated products

### ISSUE THREAD

**Issue by acidjunk** [firebearstudio/importexportfree#12]
I'm looking into buying the extension. Two questions:
- Can you explain the flow regarding the cache: what will customers see during the import: will the performance of the shop degrade during import?
- If products and categories are updated; will the order history, e.g. the info a customer can lookup about their orders, always stay intact?

**Comment by acidjunk** [comment]
Thanks for the answer.

**Comment by biotech** [comment]
Hello @acidjunk !

Sorry for delay and that issue was closed without answer during new release and cleanup here. 

1. Performance of shop can degrade during the import only if server have not enough capacity and server resources to run import process and Magento 2 store front in same time. That mean that until import process is completed - cache tags / types stay unaffected. After import process is completed - Magento run partial reindexes for affected products which also should clean cache by tags of that products. 

2. When order created - product price, name and other data are copied to another data base table so order data will stay unaffected even if it was updated during the import

Thanks for your patience and questions!
